"""initial schema

Revision ID: 4ed8aed199b1
Revises: 
Create Date: 2025-12-08 01:54:44.139665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed8aed199b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price_bonus', sa.Integer(), nullable=False),
    sa.Column('price_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('CHILD', 'PARENT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('last_app_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bot_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('resulting_balance', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GAME_CLICK', 'REFERRAL', 'SHOP_PURCHASE', 'ADMIN_ADJUST', 'AMOCRM_BONUS', 'OTHER', name='transaction_type'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_transactions_user_id'), 'balance_transactions', ['user_id'], unique=False)
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MANUAL', 'AUTO_INACTIVE', name='broadcast_type'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('keyboard_json', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'CANCELED', name='broadcast_status'), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_created_by_admin_id'), 'broadcasts', ['created_by_admin_id'], unique=False)
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('last_click_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicks_today', sa.Integer(), nullable=False),
    sa.Column('clicks_today_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PENDING_PAYMENT', 'PAID', 'CANCELED', 'FULFILLED', name='order_status'), nullable=False),
    sa.Column('total_bonus', sa.Integer(), nullable=False),
    sa.Column('total_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.Enum('BONUS_ONLY', 'CARD_ONLY', 'MIXED', name='payment_method'), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('amocrm_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_amocrm_lead_id'), 'orders', ['amocrm_lead_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_phone'), 'orders', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reward_given', sa.Boolean(), nullable=False),
    sa.Column('reward_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_invited_user_id'), 'referrals', ['invited_user_id'], unique=True)
    op.create_index(op.f('ix_referrals_inviter_user_id'), 'referrals', ['inviter_user_id'], unique=False)
    op.create_table('amo_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amocrm_event_id', sa.String(length=255), nullable=True),
    sa.Column('amocrm_lead_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROCESSED', 'ERROR', name='amo_transaction_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amocrm_event_id', name='uq_amo_transactions_amocrm_event_id')
    )
    op.create_index(op.f('ix_amo_transactions_amocrm_event_id'), 'amo_transactions', ['amocrm_event_id'], unique=False)
    op.create_index(op.f('ix_amo_transactions_amocrm_lead_id'), 'amo_transactions', ['amocrm_lead_id'], unique=False)
    op.create_index(op.f('ix_amo_transactions_order_id'), 'amo_transactions', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_bonus', sa.Integer(), nullable=False),
    sa.Column('unit_price_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_amo_transactions_order_id'), table_name='amo_transactions')
    op.drop_index(op.f('ix_amo_transactions_amocrm_lead_id'), table_name='amo_transactions')
    op.drop_index(op.f('ix_amo_transactions_amocrm_event_id'), table_name='amo_transactions')
    op.drop_table('amo_transactions')
    op.drop_index(op.f('ix_referrals_inviter_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_invited_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_amocrm_lead_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('game_stats')
    op.drop_index(op.f('ix_broadcasts_created_by_admin_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_table('balances')
    op.drop_index(op.f('ix_balance_transactions_user_id'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('news')
    # ### end Alembic commands ###
